### ISSUE TITLE
Add the option of fetching the coverage from the image created with t2d --deployv

### ISSUE THREAD

**Issue by hbto** [Vauxoo/travis2docker#178]
in the previous version of t2d, that is t2d with --deployv switch, 

We were able to fetch a coverage report with the following command:

```
coverage report -m

```

Can we have it back in order to assess how are we increasing/decreasing the coverage of our development without having wait for the CD. This will have a good side effect reduce the number of job in the CD only to know the coverage.

Regards.

**Comment by moylop260** [comment]
For record,
we need to migrate the `coverage` command:
 - https://git.vauxoo.com/devops/vxci/blob/f15e10854907f51911725cb68/vxci/common.py#L610

And generates coveragerc content:
 - https://git.vauxoo.com/devops/vxci/blob/f15e10854907f51911725cb68d01232a6ccd8b4c/vxci/common.py#L699

And get the same coveragerc file:
 - https://git.vauxoo.com/devops/vxci/blob/f84d1a9c0c64ed38c6c5498b6949da54048e321d/vxci/templates/coveragerc#L1

It could be migrated to tools_test file in order to be able to re-use it in t2d:
 - https://git.vauxoo.com/devops/vxci/-/blob/master/vxci/tools_test.py

**Comment by antonag32** [comment]
The idea is to have everything autoconfigured. So that as stated, when running the command `coverage run` or `coverage report -m`, you can automatically regenerate coverage data or see the coverage report.

The commands must simply _work_. So for example, the result should be the same regardless of the current working directory. It should also use the customization each repo has in their `variables.sh`.

To do this, environment variables will used (for the most part), for example `COVERAGE_HOME` or `COVERAGE_RCFILE` to specify the configuration file to be used. Some of this variables can be directly set from the Dockerfile, some others (for examples modules to run) are more complicated and will probably need to be computed and set during the installation process in `build.sh`.

**Comment by moylop260** [comment]
For record,

It is working like a charm
 - <img width="1534" alt="Screenshot 2022-10-26 at 10 27 14" src="https://user-images.githubusercontent.com/6644187/198068807-5e6a95e7-b8a5-4bbb-b1b7-01d2ecaddaaa.png">


Thank you @antonag32
