### ISSUE TITLE
Advice that directory /home/odoo/.cache Needs permission update

### ISSUE THREAD

**Issue by hbto** [Vauxoo/travis2docker#186]
When first running pre-commit-vauxoo

It tries to create new folders at directory /home/odoo/.cache/

But in doing so an Exception is raised:
```

PermissionError: [Errno 13] Permission denied: '/home/odoo/.cache/

```

![Screenshot 2022-10-28 at 3 07 13](https://user-images.githubusercontent.com/7598010/198537907-a5059ef4-da3c-40f3-a7f8-f80e93e2abfe.png)

Changing ownership on folder from root to odoo is needed

```
chown -R odoo:odoo /home/odoo/.cache/ 
```

as directory is owned by root:
![Screenshot 2022-10-28 at 3 11 14](https://user-images.githubusercontent.com/7598010/198538221-a1b8b5d0-bade-43c0-a11a-c6437da81d10.png)

It would be good to have this advice when running t2d

```

docker exec -it --user=root CONTAINER chown -R odoo:odoo /home/odoo/.cache/ 

```

Regards.

**Comment by moylop260** [comment]
@antonag32 

This folder can be changed during the image build since it is not a volume (I think so)

Could you check what particular folders or files in the /home/odoo path has root permissions in order to run chown from the Dockerfile, please?

e.g.  `chown -R odoo:odoo /home/odoo/.config` from https://github.com/Vauxoo/travis2docker/issues/172

Also, the following path is missing in the PATH `/home/odoo/.local/bin`

**Comment by moylop260** [comment]
BTW
Maybe something is not working well here:

 - https://github.com/Vauxoo/travis2docker/blob/53beaaa58b7ac3296adbdfcfbb0c3bc6783fb4e2/src/travis2docker/templates/build.sh#L178

Notice we don't like to run `chown -R odoo:odoo /home/odoo/` because of it spends a lot of time and almost of the path already have odoo permission

**Comment by luisg123v** [comment]
FYI @allanpa88

**Comment by antonag32** [comment]
@moylop260 

I don't think we can place it in the Dockerfile since these folders are not part of the base install, but are generated by optional programs, like vim.

In this case `.cache` being owned by root is caused by choosing installing the `ctrpl` plugin for vim.
`/home/odoo/.spf13-vim-3` is also owned by root but I don't think that causes any problems.

I also could not find `/home/odoo/.config`, on the images I created. What program is using that directory?

**Comment by moylop260** [comment]
You can use a find with `not user`
 - `find /home/odoo -not -user moylop260 -depth 1 -exec chown -R odoo:odoo {} \;`

**Comment by moylop260** [comment]
FYI `$HOME/.cache` is a generic folder used from pre-commit, pip and so on
