### ISSUE TITLE
Error to download  git.vauxoo.com 

### ISSUE THREAD

**Issue by cesar2000ab** [Vauxoo/travis2docker#196]
Version:

![image](https://user-images.githubusercontent.com/44850827/219876007-14e346d3-12fd-4a7b-8d2f-8ced9ee4b331.png)

Video:

https://grupoabsa.zoom.us/rec/share/IJPnHunVbPvXcviGNQnYFUjtpzncc8Cdyax6wGXcgHcUPh-axkd0MmhwUCIzJbuw.16Z4HSqmJRmK87aO?startTime=1676735713000
Código de acceso: wYDdGh4@

**Comment by moylop260** [comment]
@cesar2000ab 

Thank you for your issue report!

I have already reproduced it locally in similar conditions:
 - <img width="1439" alt="Screenshot 2023-02-18 at 14 44 23" src="https://user-images.githubusercontent.com/6644187/219898759-3d0c1c62-8028-4282-97b7-6b7ba099f48f.png">

The steps to reproduce it were:
 - `t2d git@git.vauxoo.com:absa/absa.git 12.0
 - `~/.t2d/script/git_git.vauxoo.com_absa_absa.git/12.0/3_5/env_1_job_1/10-build.sh --no-cache`

It is similar to your video

We have deployed new changes in the t2d tool and we are using the same image as DeployV to match the CI with the CD with fewer variants

The new way needs 2 things:
1) Extra parameter `--deployv`
2) Request access to `quay.io`

I mean, running the commands:
 - `t2d --deployv git@git.vauxoo.com:absa/absa.git 12.0` 
 - `~/.t2d/script/git_git.vauxoo.com_absa_absa.git/12.0/3_5/env_1_job_1/10-build.sh --no-cache`

You will see the following output:

```txt
Generated scripts:
- ~/.t2d/script/git_git.vauxoo.com_absa_absa.git/12.0/3_5/env_1_job_1
================================================================================
Using --deployv option you will need to run the following extra step manually after to create the container or after running 20-run.sh script
docker exec -it --user=root CONTAINER find /home/odoo -maxdepth 1 -not -user odoo -exec chown -R odoo:odoo {} \;

TIP: Use the parameter "--docker-image=quay.io/vauxoo/PROJECT:TAG" get the PROJECT:TAG info in your "build_docker" pipeline similar to
"... INFO  - deployv.deployv_addon_gitlab_tools.common.common.push_image - Pushing image ... to quay.io/vauxoo/PROJECT:TAG"
Sending build context to Docker daemon  3.601MB=================================Sending build context to Docker daemon  557.1kB
Step 1/20 : FROM quay.io/vauxoo/absa:absa-12.0-bc1d6c2
absa-12.0-bc1d6c2: Pulling from vauxoo/absa
8f12f7a5869b: Downloading [=======================================>           ]  5.436GB/6.828GB
...
```

Notice the step 1/20 is using docker image called `quay.io/vauxoo/absa:absa-12.0-bc1d6c2` instead of old `vauxoo/odoo-80-image-shippable-auto`

The quay image is built from your CI and it is the same one used in deployv staging instances in the CD

So, request your project manager access to be able to download images from quay.

You can double-confirm if you have access using the following command:

 - `docker pull quay.io/vauxoo/absa:absa-12.0-bc1d6c2`

Before you need to log in with

`docker login quay.io`

your user and password

Also, consider that the extra comments in the output of t2d command as:
`docker exec -it --user=root CONTAINER find /home/odoo -maxdepth 1 -not -user odoo -exec chown -R odoo:odoo {} \;`

So, after creating the container you will need to run this extra command (replace CONTAINER by the real name of your CONTAINER)

**Comment by cesar2000ab** [comment]
tks Moy,
Is neccesary that all Dev from ABSA IT has access to this quay.io/vauxoo/absa:absa-12.0-bc1d6c2

I run.
~/.t2d/script/git_git.vauxoo.com_absa_absa.git/12.0/3_5/env_1_job_1/10-build.sh --no-cache

and show the:

![image](https://user-images.githubusercontent.com/44850827/220177805-322ba999-3166-4951-93ac-5d44b9cd6099.png)

**Comment by moylop260** [comment]
> Is neccesary that all Dev from ABSA IT has access to this quay.io/vauxoo/absa:absa-12.0-bc1d6c2

Yes, it is.

It is related to my comment:

> So, request your project manager access to be able to download images from quay.

I mean, you need to contact your project manager or support team in Absa to request access to https://quay.io/ Absa project with all your dev users

Regards!
