### ISSUE TITLE
When using --deployv option and providing the $START_SSH variable, the SSH service is not started

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/travis2docker#200]
Previously, we supported the `$START_SSH="1"` variable to indicate the SSH service to be started automatically on created containers.

Since we now use the `--deployv` option, such variable doesn't work anymore, I'm guessing due to the used image.

CC @antonag32 @moylop260

**Comment by antonag32** [comment]
Yes, seems like deployv images don't come with `sshd` setup, at least the ones I have used. I am thinking this can be passed as a build argument to Docker and if enabled ssh can be configured during the image building process.

**Comment by moylop260** [comment]
I think vxci or deployv is using this way

But we are using the docker image directly

So, we could copy that part from vxci

Also, using ssh only you need to install the package and start the service

I think it could be executed manually directly into  the container from the user since that not all the cases you need to connect using ssh and you could need to install ngrok and add keys too

ssh installed doesn't work by itself

Could you elaborate the case of use where it adds value in your workflow of the day, please?

**Comment by luisg123v** [comment]
We wouldn't need to install anything. A clean t2d container already has the SSH server installed, it's just not started automatically.

If I create a new one and run:

`service ssh start`

It starts to run.

My use case is, I use SSH to connect tools to be able to edit and develop.

**Comment by moylop260** [comment]
I got it

It was directly in the old docker image
 - https://git.vauxoo.com/vauxoo/docker-odoo-image/blob/4122fa6d17d30ed98ae6b1fdedbcd529bde3fcab/odoo-shippable/scripts/entrypoint_image#L69

Maybe it could be done from the same way than start_psql & start_odoo:
 - https://github.com/Vauxoo/travis2docker/blob/b27a738f20def425a64faf96e3d21a1e4f581507/src/travis2docker/templates/entrypoint_deployv.sh#L105

What do you think @luisg123v ?

**Comment by luisg123v** [comment]
oh, I like that way!

**Comment by moylop260** [comment]
@antonag32 

So, let's do it, please
