### ISSUE TITLE
[BUG] False positives on database creation failures

### ISSUE THREAD

**Issue by lasley** [Vauxoo/travis2docker#53]
Hi Friends,

Something I've noticed with Travis2Docker is that if a build is severely broken, such as in the instance of a missing XML ID, the build itself shows as passing.

Example:
* Travis fail - https://travis-ci.org/laslabs/vertical-medical/jobs/143141347
* Runbot pass - https://runbot.laslabs.io/runbot/build/1895
* Runbot logs - https://runbot.laslabs.io/runbot/static/build/01895-feature-c0d4f0/logs/job_20_test_all.txt

Not sure how long the Runbot links will preserve but an easy way to replicate is to just change a few letters in an XML data reference, or something equally catastrophic. Basically anything that breaks the database after some tests have already completed.

Let me know if you need more info!

**Comment by moylop260** [comment]
It's is a issue of runbot, because runbot don't process the returned-code from script executed.
Just process the log base on [regex](https://github.com/odoo/odoo-extra/blob/a28950c1deee9b4167fa266051b5352b8323f191/runbot/runbot.py#L45-L46) and [Modules loaded log message](https://github.com/odoo/odoo-extra/blob/a28950c1deee9b4167fa266051b5352b8323f191/runbot/runbot.py#L982)

Now, the runbot log that you are using have unbuffer (colorized output) and the regex don't support this case.

Try using the param [-e UNBUFFER=0](https://github.com/Vauxoo/runbot-addons/blob/d88e5f9846252bc9f20fc9d4a537a660eb232a46/runbot_travis2docker/models/runbot_build.py#L167) in build run.

**Comment by lasley** [comment]
Ah understood, thanks @moylop260. I'll check out the unbuffer then submit a patch against runbot_travis2docker if it fixes.
